### ISSUE TITLE
Add a copy of the MIT license to the repository

### ISSUE THREAD

**Issue by Calinou** [Ducking-Games/godotons#16]
Could you add the [MIT license text](https://choosealicense.com/licenses/mit/) in a file called `LICENSE.md` at the top-level? Having just *"License: MIT in `README.md`"* may not be considered enough to be legally binding.

**Comment by asciifaceman** [comment]
Oh yes, that was supposed to be in here but I think it got removed on accident. I'll fix that up when I have the chance later today!

Thanks @Calinou

**Comment by CaffeinatedCM** [comment]
Added in [b50d5da](https://github.com/Ducking-Games/godotons/commit/b50d5da3e58069b97ed07b548fc317c806efdbca)
